# ~/.zshrc — minimal, fast zsh config
# Generated by Windows post-install setup (2026-04-26)

# PATH
export PATH="$HOME/.local/bin:$PATH"

# History
HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
setopt SHARE_HISTORY HIST_IGNORE_DUPS HIST_IGNORE_SPACE EXTENDED_HISTORY

# Completion
autoload -Uz compinit && compinit
zstyle ':completion:*' menu select
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}'

# Key bindings (emacs-style; use 'bindkey -v' for vi)
bindkey -e

# Plugins
source ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh
source ~/.zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# Modern CLI tool aliases
alias ls='eza --group-directories-first'
alias ll='eza -lh --group-directories-first --git'
alias la='eza -lah --group-directories-first --git'
alias tree='eza --tree'
alias bat='batcat'

# fzf integration
[ -f /usr/share/doc/fzf/examples/key-bindings.zsh ] && source /usr/share/doc/fzf/examples/key-bindings.zsh
[ -f /usr/share/doc/fzf/examples/completion.zsh ] && source /usr/share/doc/fzf/examples/completion.zsh

# zoxide (smarter cd: 'z projectname' jumps to most-frecent match)
eval "$(zoxide init zsh)"

# Starship prompt
# Shell identifier (read by starship.toml env_var module)
export STARSHIP_SHELL_LABEL="DEBIAN-WSL2"

# Set terminal background (OSC 11) - dark red
printf '\033]11;#1a0000\007'

eval "$(starship init zsh)"

# Tell terminal emulator (WezTerm, etc.) the current working directory via OSC 7.
# Without this, WezTerm's "new tab in current domain" can't track where you are
# and falls back to the spawn cwd — opening new WSL tabs at /mnt/c/Users/zlome
# instead of wherever you cd'd to.
_wezterm_osc7() {
    printf '\e]7;file://%s%s\e\\' "${HOSTNAME}" "${PWD}"
}
typeset -ag chpwd_functions
chpwd_functions+=(_wezterm_osc7)
_wezterm_osc7
